Implement failures.c
hmathieu-insat/PIR pull request #71
Opened 2022-05-14 11:10 UTC by Tsjerfell

Fixes #67

2022-05-15 10:28 UTC, hmathieu-insat requested changes
Did you implement the software timer, I couldn't find the corresponding commit if you did.
Some changes to tend to I think but shouldn't take long.

2022-05-15 10:28 UTC, hmathieu-insat commented on Nouveau PIR/firmware/source/failures.c
> +			TIM_Cmd(TIM1, ENABLE);  //Enable timer1 (formerly Timer6 on microchip)
Why?
On the google sheet, timer6 on microchip is said to correspond with Timer3

2022-05-15 10:28 UTC, hmathieu-insat commented on Nouveau PIR/firmware/source/failures.c
>  		{
(The one based on our Timer1)

2022-05-15 10:28 UTC, hmathieu-insat commented on Nouveau PIR/firmware/source/failures.c
> +				TIM_Cmd(TIM8,DISABLE); //TODO: #77 Port with systick
This should be ported with the systick (we have no Timer8 on the microchip)
[#77](https://github.com/hmathieu-insat/PIR/issues/77)

2022-05-15 10:28 UTC, hmathieu-insat commented on Nouveau PIR/firmware/source/failures.c
> +					if(angle_to_edge_CAM_delay[cam_id][i] + ((double)(shift_counter_CAM_delay[cam_id][i] - 1) + ((double)((unsigned long)TIMGetCounter(TIM4) + timer_overflow_CRK*(unsigned long)(TIM2->ARR)))/former_
Shouldn't the software based timer implement this?

2022-05-21 10:11 UTC, Tsjerfell commented on Nouveau PIR/firmware/source/failures.c
> +			TIM_Cmd(TIM1, ENABLE);  //Enable timer1 (formerly Timer6 on microchip)
You're absolutely right

2022-05-21 10:30 UTC, Tsjerfell commented on Nouveau PIR/firmware/source/failures.c
>  		{
It indeed should

2022-05-22 14:40 UTC, hmathieu-insat requested changes
Apart from 1 remark, seems all good to me

2022-05-22 14:40 UTC, hmathieu-insat commented on Nouveau PIR/firmware/source/failures.c
> +		//TODO: #78 There is a deactivation + reset of former timer4 (new software implemented timer) to implement here
TODO has not been addreesed here unless I'm mistaken

2022-05-22 15:13 UTC, hmathieu-insat approved these changes

2022-05-22 15:20 UTC, merged